### ISSUE TITLE
[deploy] - Configurações default do tema

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/phpsp-blog-theme#30]
Toda vez que fazemos um deployment temos que manualmente arrumar o menu e a imagem do header. Temos que ter uma solução menos "sobrinho" que essa.

**Comment by pauloelr** [comment]
:+1:

**Comment by williamespindola** [comment]
Vale lembrar que nossos recursos são limitados para isto. Minha intenção quando criei o repo do tema era atualizar tudo automaticamente com um PR para o master, mas o site esta no azure que não é possível fazer isto la. Tomei a decisão então de subir o tema da forma que é hoje assim não precisa de apenas uma pessoa para fazer, qualquer um disponível que tem acesso ao painel do blog pode fazer.

Agora eu te pergunto, ha algum hook to WorpPress que executa algum script durante a instalação do tema? Eu não conheço...

**Comment by jpjoao** [comment]
Então, eu pensei justamente nesse hook de instalação... Pesquisei um pouco e acho que teríamos que fazer um "combo".
Há uma função para quando o tema é ativado/atualizado: https://codex.wordpress.org/Plugin_API/Action_Reference/after_switch_theme
Mas nesse ponto acredito que as configurações do tema anterior já tenham sido jogadas fora.
Há uma função para quando o tema esta sendo desativado:
https://codex.wordpress.org/Plugin_API/Action_Reference/switch_theme
A ideia seria fazer o tema, ao ser desativado, "colocar em stage" as configurações para que o próximo, quando ativado, possa pegar essas informações.

Além disso, quero dar uma estudada em como fazer uma atualização do tema corretamente. Mesmo que subindo o zip, eu acho que a configuração deveria se manter automaticamente. Pode ser apenas um problema no processo. Qual que é o processo? Muda o nome da pasta do antigo, sobe o novo? Ou sobrescreve o antigo com o novo? Quero reproduzir localmente para testar e tentar resolver.

**Comment by jpjoao** [comment]
Para a imagem do header, eu estou dando uma simplificada na lógica pra pegar a imagem lá e adicionei um fallback para a imagem padrão do tema. Isso quer dizer que teremos uma coisa a menos para se preocupar. Quando mudar a imagem padrão basta mudar ela também no tema e pronto. =)

As configurações do meu estou investigando ainda se consigo colocar um default também.
