### ISSUE TITLE
Como administrador do site gostaria de ter uma camada cache para servir as páginas mais rapidamente

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/phpsp-blog-theme#54]
Diminui o tempo de load das páginas e libera mais recursos do servidor para outras atividades

**Comment by jpjoao** [comment]
To pensando em colocar esse plugin aqui:
https://wordpress.org/plugins/w3-total-cache/

Já usei quando trampava em agência e ele da uma bela ajuda

**Comment by gabrielrcouto** [comment]
Concordo totalmente em ter algo para o cache @jpjoao. Atualmente no que faço uso o https://wordpress.org/plugins/wp-super-cache/, ele é mais básico que o W3 mas deu menos problema com conflitos com outros plugins.

**Comment by williamespindola** [comment]
De acordo, faz tempo que vejo que o site inteiro é lento. Mas será que não é o servidor?

**Comment by jpjoao** [comment]
Vou testar localmente o que o @gabrielrcouto sugeriu que parece ser, de fato, bem mais simples. Se tudo correr bem faço o PR e testo.

@williamespindola Pode até ser que seja o servidor, mas por hora não tenho acesso nenhum a ele então vamos com o que temos :p Se mesmo com cache o site continuar lento aí partimos para o módulo mais completo e/ou server tunning.

**Comment by williamespindola** [comment]
yep! certamente o cache vai da um up. Se precisar de alguma ajuda da um grito.

**Comment by jpjoao** [comment]
Hoje vou testar local. Se tudo der certo amanha às 7h eu testo no site. Acho que pra nossa comunidade faz mais sentido testar de manhã que de noite / madrugada.

**Comment by jpjoao** [comment]
Seguindo a sugestão do @gabrielrcouto o wp-super-cache esta instalado e rodando. Configurações padrão (as recomendadas) exceto a que explicita que o cache esta sendo usado (baseado na premissa de que quanto menos entregar do que esta usando "mais seguro" - apesar que escrever isso no git do site não é esconder nada... enfim..)

**Comment by hussani** [comment]
Boa! Site voando agora!
