### ISSUE TITLE
Como membro da comunidade quero que a listagem de últimos artigos não traga o post atual

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/phpsp-blog-theme#55]
Assim teremos 5 conteúdos a mais para chamar a atenção do visitante

**Comment by hussani** [comment]
:+1:

**Comment by hussani** [comment]
Creio também que o visual ficará mais limpo se houver algum tipo de espaçamento entre os posts, e que pode ficar ainda mais limpo caso não haja imagens de autores, como nas imagens anexas.
![captura de tela 2015-07-28 as 14 32 47](https://cloud.githubusercontent.com/assets/959130/8940306/95d56fa6-353f-11e5-9969-6832ecc876a1.png)
![captura de tela 2015-07-28 as 14 37 50](https://cloud.githubusercontent.com/assets/959130/8940309/95f0e20e-353f-11e5-9f64-d7f8e618aacf.png)
