### ISSUE TITLE
Mudança no sistema de comentários

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/phpsp-blog-theme#60]
Não vejo comentários há um bom tempo no blog.

A relevância do Discuss ainda é válida? Deveríamos mudar para comentários pela conta do Facebook ou de volta para o "padrão" do Wordpress?

O quanto que isso melhoraria ou não a usabilidade / uso real da ferramenta (comentários)?

**Comment by nawarian** [comment]
Eu acho até estranho esse Discuss... não curto muito. Se pudessemos fazer com o Facebook diretamente seria bacana.

**Comment by hussani** [comment]
Honestamente eu gosto do Disqus. Ele fornece o "recent posts" de maneira prática, pode ser personalizado com facilidade e o que acredito que é o melhor dele, ele foi feito pra gerir comentários.

De todas as opções, ele é o mais personalizável. Acho legal que ele continue como o serviço de comentários do blog.

**Comment by gabrielrcouto** [comment]
Eu voto no Facebook, mais simples e todo mundo se sente a vontade de usar.

**Comment by gabidavila** [comment]
Eu prefiro o Disqus. Nem todo mundo quer usar sua conta do FB pra isso, acho ele menos "forçado" que usar o FB por default.

**Comment by rogeriopradoj** [comment]
Eu gosto e prefiro o Disqus. 

Gosto principalmente por dar para o usuário uma série de opções de login.

Nao gosto da opção apenas Facebook,  ou apenas Twitter, ou mesmo apenas wordpress. 

@jpjoao: conhece algum jeito de ter login via Facebook no Disqus?

**Comment by marcelgsantos** [comment]
Eu também gosto e prefiro o Disqus! 

Concordo com o @hussani, acho que ele é o mais personalizável e ele é de fato uma ferramenta para gerenciar comentários. Voltar para o do Wordpress acredito que seja um tiro no pé pois ele abriria porta para "spams" e teria um trabalho maior para instalar e configurar. Sobre o Facebook, nunca utilizei e não sei se me sentiria confortável para utilizá-lo em comentários, IMHO.

Acho difícil que o problema da falta de comentários seja por conta do sistema de comentários. O Laracasts, o TutsPlus, o Sitepoint, o Tableless utilizam o Disqus e acontece bastante comentário nestes sites. Acredito que o problema seja outro!

Alguns questionamentos podem ajudar a entender a falta de comentários. São eles:

1. O site possui uma alta taxa de acesso que respalde um grande número de comentários?
2. Qual é o alcance do site? Ele é conhecido o suficiente para possibilitar mais comentários?
3. O que está procurando quem visita o site do PHPSP? Eventos, meetups, artigos?
4. Os assuntos despertam interesse que motiva o leitor a comentar?

Estes questionamentos são o ponto inicial para entender este comportamento. Acredito que ferramentas como o Google Analytics e uma ferramenta de mapa de calor como o Hotjar ou CrazzyEgg pode ajudar a entender melhor porque isso acontece!

**Comment by jpjoao** [comment]
Colocamos o GA ontem no site. Não tenho ideia ainda da quantidade de acessos nem nada.

Eu, particularmente, não sou um "comentador". Então tanto faz a ferramenta, raramente (pra não dizer nunca e queimar a lingua um dia) eu comento. Eu não acho que faria um novo cadastro / login apenas para comentar.

Abri a discussão justamente por ver que não há praticamente nenhum comentário acontecendo no site atualmente. O problema pode ser tanto a ferramenta / meio para comentar, o tipo de conteúdo ou o tipo de visitante que temos. Se o conteúdo não é "comentável", se o usuário médio não é "comentador" a ferramenta não fará milagres.

Sobre os "recent posts" tem inúmeras ferramentas pra WP que fazem o papel e talvez até de uma forma melhor, é questão primariamente de organizar o conteúdo, taggear corretamente os posts e aí sim saber o que é semelhante ou não.

**Comment by williamespindola** [comment]
Discus 4
Facebook 2

A minha é manter no discus, afinal com ele da para compartilha no facebook e outras redes.

Como a maioria prefere o discus vou fechar esta issue. Caso o assunto volte a tona reabrimos.
