### ISSUE TITLE
Fix mixed content site (non secure)

### ISSUE THREAD

**Issue by rogeriopradoj** [PHPSP/phpsp-blog-theme#70]
https://www.jitbit.com/sslcheck/#url=https://phpsp.org.br/

![image](https://user-images.githubusercontent.com/443391/34284211-82c4b0b2-e6b7-11e7-9633-38e850aacb36.png)

![grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo___grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo](https://user-images.githubusercontent.com/443391/34284215-8712d338-e6b7-11e7-9387-c9535b6fb834.png)

![grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo___grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo_and_slack_-_phpsp](https://user-images.githubusercontent.com/443391/34284218-89d1ebae-e6b7-11e7-8ee4-bff3fbea8f9b.png)

![grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo___grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo_and_slack_-_phpsp 1](https://user-images.githubusercontent.com/443391/34284221-8cc3adc0-e6b7-11e7-910b-ce38a55ea96e.png)

![grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo___grupo_de_desenvolvedores_de_php_do_estado_de_sao_paulo_and_slack_-_phpsp 2](https://user-images.githubusercontent.com/443391/34284225-905090a2-e6b7-11e7-9141-5597b3ed4d42.png)

**Comment by williamespindola** [comment]
Esta aparecendo tudo ok aqui, certificado válido que expira 21 Julho de 2018

**Comment by rogeriopradoj** [comment]
@williamespindola o problema não está no certificado, mas sim em ter partes do site chamando recursos não-https, o tal do mixed content.

Pode dar uma olhada aqui para mais informações sobre o assunto: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by rogeriopradoj** [comment]
https://gist.github.com/rogeriopradoj/07ad1be5b6e5fbb7c5e79e559a2ba66a

**Comment by williamespindola** [comment]
Entendi @rogeriopradoj sei deste problema. Falei que estava normal pois visitei o link que você passou e apareceu que estava normal la. Realmente era para aparecer estes erros. Bom agora que você colocou o docker vai ficar mais fácil de fazer o setup e trabalhar neste tema, estou empurrando com a barriga a bastante temp para fazer alguma coisa por aqui, pois instalação do wordpress local com o tema estava meio chata :D 
Lets do this!

**Comment by rogeriopradoj** [comment]
Blz, @williamespindola !

Estou trabalhando agora nisso já, o que já fiz:
- no cloudflare:
    - troquei o tipo de ssl de full para flexible, [src](https://www.shoutmeloud.com/fix-mixed-content-error-wordpress-adding-ssl-certificate.html)
    - liguei a opção "Automatic HTTPS Rewrites"

- no wordpress:
     - mudei a url padrão do site para https://phpsp.org.br
     - instalei o plugin [Cloudflare](https://wordpress.org/plugins/cloudflare/)
     - instalei o plugin [Cloudflare SSL by Weslink](https://wordpress.org/plugins/ctw-ssl-for-cloudflare/)

O que estou fazendo agora, daqui a pouco peço para vocês validarem:
- ajustando o theme
    - fonts Google como https
    - colocar a imagem do dev na estrada dentro do tema
    - atualizando a imagem da locaweb
    - publicando nova versão (1.6.4 ou 1.7.0 ?)

**Comment by rogeriopradoj** [comment]
@williamespindola fechado!!!

Fiz os ajustes no tema, e, usando git-flow, versão 1.7.0.

Já subi no servidor essa versão do tema no wordpress e ativei, agora, sem problemas!

**Comment by williamespindola** [comment]
Show de código!
